# Generated by Django 2.2.7 on 2019-11-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='confirm_Password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='user_name',
            field=models.CharField(default='dame', max_length=60),
            preserve_default=False,
        ),
    ]
